export const ActionTypes = {
  SET_REPOS_NAME     : 'SET_REPOS_NAME',
  SET_GITHUB_REPOS   : 'SET_GITHUB_REPOS',
  GET_LANGUAGE_URL   : 'GET_LANGUAGE_URL',
  SET_LANGUAGE       : 'SET_LANGUAGE',
  SET_SPECIFIC_REPOS : 'SET_SPECIFIC_REPOS'
}